name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
      - name: Run Python tests with coverage
        run: |
          pytest --cov=python/solutions --cov-report=xml python/tests

  ruby-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: |
          bundle install || true # In case you don't have a Gemfile
      - name: Run Ruby tests with coverage
        run: |
          cd ruby && bundle exec ruby tests/test_euler001.rb
